### ISSUE TITLE
switch user doesn't work

### ISSUE THREAD

**Issue by cctgteddy** [l3-team/CasGuardBundle#1]
Here is part of my security.yaml  
```yaml
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: true
            lazy: true
            security: true
            guard:
                authenticators:
                    - cas.security.authentication.authenticator
```

adding ?_switch_user=targetuser to the URL works.  I have intercept redirects turned on and on the intercept page it shows me as authenticated as the target user but when I follow the redirect it is gone.

Am I missing something? Thanks in advance

![image](https://user-images.githubusercontent.com/60752051/203865235-2ecb1f1a-eefd-42ab-aa9e-0fe228bcf4f6.png)
